

all:
	cd ./src/atsread;     make -f Makefile.linux
	cd ./src/ats_noisy~;  make -f Makefile.linux
	cd ./src/ats_sinnoi~; make -f Makefile.linux
	cd ./src/oscbank~;    make -f Makefile.linux
	
clean: 
	cd ./src/atsread;     make -f Makefile.linux clean
	cd ./src/ats_noisy~;  make -f Makefile.linux clean
	cd ./src/ats_sinnoi~; make -f Makefile.linux clean
	cd ./src/oscbank~;    make -f Makefile.linux clean

